Some weights of the model checkpoint at albert-base-v2 were not used when initializing AlbertForSequenceClassification: ['predictions.bias', 'predictions.LayerNorm.weight', 'predictions.LayerNorm.bias', 'predictions.dense.weight', 'predictions.dense.bias', 'predictions.decoder.weight', 'predictions.decoder.bias']
- This IS expected if you are initializing AlbertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPretraining model).
- This IS NOT expected if you are initializing AlbertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of AlbertForSequenceClassification were not initialized from the model checkpoint at albert-base-v2 and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
using device cuda
Using custom data configuration default
0
  0%|                                                                                                                                                                                            | 0/9427 [00:00<?, ?it/s]  0%|                                                                                                                                                                                            | 0/9427 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 106, in <module>
    train_dataset = get_dataset(name="boolq", tokenizer=tokenizer, split='train')
  File "main.py", line 46, in get_dataset
    input_ids[0][i] = tensor_features['input_ids']
IndexError: index 0 is out of bounds for dimension 0 with size 0
